config/routes.rb
Rails.application.routes.draw do

  root 'houses#index'
  resources :houses do
      resources :projects, only: [:index, :new]
  end


  resources :projects do
    resources :items, only: [:index]
  end
  get 'insufficient_quantity', to: 'projects#insufficient_quantity'

  resources :materials do
    collection do
      delete'remove_multiple_materials' => 'materials#remove_multiple'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"} do
    resources :users, :only => [:show]
  end

  get '/projects/materials/new' => 'materials#new'
  get '/materials/:id/blah', to: 'materials#blah'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :house
  has_many :items
  has_many :materials, through: :items
  validates :name, presence: true
  validates :name, uniqueness: true

  def materials=(material_hash)
    if material_hash[:name] != ""
      material = Material.find_or_create_by(name: material_hash[:name])
      material.quantity_on_hand = material_hash[:quantity_on_hand].to_i
      material.save
      self.save
      self.add_item(material.id, material.quantity_on_hand)
    end
  end

  def items_attributes=(items_attributes)
     items_attributes.values.each do |item|
       self.add_item(item[:material_id], item[:quantity])
     end
  end

  def add_item(material_id, quantity)
    quantity = quantity.to_i

    if quantity > 0
      material = Material.find(material_id)
      if self.items.exists?(material_id: material_id)
        item = self.items.find_by(material_id: material_id)
      else
        item = self.items.new(material_id: material_id)
      end

      item.quantity = quantity
      item.save
    else

      if self.materials.exists?(material_id)
        item = self.items.find_by(material_id: material_id)
        self.items.delete(item)
      end
    end

    self.save
  end

  def set_status(status)
    self.status = status
    self.save
  end


  def build_items_list
    Material.all.each do |material|
      if !self.materials.exists?(material.id) #Only build item if not already included
        self.items.new(material_id: material.id)
      end
    end
  end

  def self.materials_shortage
    @short_projects = []
    self.all.each do |project|
      project.items.each do |item|
        if Material.find(item.material_id).quantity_on_hand < item.quantity
          if @short_projects.exclude?(project)
            @short_projects << project
          end
        end
      end
    end
    @short_projects
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def insufficient_quantity
    @insufficient_quantity = Project.materials_shortage
  end

  def index
    if params[:house_id]
      @house = House.find(params[:house_id])
      @projects = @house.projects
    else
      @projects = Project.all
    end
  end

  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @project.materials.to_json }
    end
  end

  def new
    @project = Project.new()
    if params[:house_id]
      @project.house = House.find(params[:house_id])
    else
      #TODO Currently there is no access through clickable means therefore redirect
      #@project.house = House.find(params[:id].to_i) would need to modify new.html.erb to include assiging a house
      redirect_to new_house_project_path(@project)
    end

    @materials = Material.all
    @project.build_items_list
  end

  def create
    @project = Project.new()
    @project.update(project_params)

    if @project.errors.messages != {}
      render 'new'
    else
      redirect_to project_path(@project)
    end

  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)

    if @project.errors.messages != {}
      render 'edit'
    else
      redirect_to project_path(@project)
    end

  end

  def destroy
    @project = Project.find(params[:id])
    @house = @project.house
    @project.delete
    @project.save
    redirect_to house_path(@house)
  end

private

  def project_params
    params.require(:project).permit(:name, :status, :house_id, materials: [:name, :quantity_on_hand], items_attributes: [:material_id, :quantity])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def item_name(item)
    Material.find(item.object.id).name
  end

  def build_items_list
    Material.all.each do |material|
      @project.items.new(material_id: material.id)
    end
  end

  def show_materials_shortage(project)
    items_list = []
    project.items.each do |item|
      material = Material.find(item.material_id)
      if material.quantity_on_hand < item.quantity
        items_list << "#{item.quantity} #{material.name} needed, #{material.quantity_on_hand} on hand"
      end
    end
    items_list
  end
  
end

app/views/projects/_project.html.erb
 <%= render 'shared/error_messages', object: f.object %>
  <p>
    <%= f.fields_for :items, @project.items do |items_list| %>
      <%= find_material_name(items_list) %>
      <%= items_list.hidden_field :material_id %>
      : quantity:<%= items_list.number_field :quantity, min: 0, placeholder: item_quantity(items_list.object.id)%>
      <br></br>
    <% end %>
  </p>

  <p>
    <%= f.fields_for :materials, @project.materials.build do |mat| %>
      New Material: <%= mat.text_field :name %>
      Quantity On Hand: <%= mat.number_field :quantity_on_hand, min: 0, placeholder: mat.object.quantity_on_hand%>

      <%= f.fields_for :items, @project.items.build do |items_builder| %>
      Quantity Needed: <%= items_builder.number_field :quantity %>
                       <%= items_builder.hidden_field :material_id, value: Material.all.last.id + 1 %>
      <% end %>

    <% end %>

  </p>

  <%= f.hidden_field :house_id, :value => @project.house.id %><br><br>
  <%= f.submit %>

  <br></br>

app/views/projects/edit.html.erb
<h2>Now Editing: <%= @project.name %></h2>

<%= form_for @project do |f| %>
  <%= render 'shared/error_messages', object: @project %>
  <%= f.label :name%>
  <%= f.text_field :name, value: @project.name %>
  <%= f.submit "Update Project" %>
<% end %>

app/views/projects/index.html.erb
<h2>Current Projects</h2>
  <ul>
    <% @projects.each do |project| %>
      <p><%= project.house.address %> </p>
      <li><%= link_to project.name, project_path(project.id) %></li>
    <% end %>
    
    <%= link_to "Projects With Insufficient Materials", insufficient_quantity_path %>
  </ul>

app/views/projects/insufficient_quantity.html.erb
<ul>
  <% if @insufficient_quantity == [] %>
    <h3>All projects have sufficient materials</h3>

  <% else %>
    <h3>Projects in need of materials</h3>


      <% @insufficient_quantity.each do |project| %>
        <p><%= link_to project.name, project_path(project) %></p>

            <% show_materials_shortage(project).each do |item| %>
              <li><%= item %></li>
            <% end %>
          <br></br>

       <% end %>

  <% end %>
</ul>

app/views/projects/new.html.erb
<h2>Add A New Project</h2>

<%= form_for @project do |f|%>
  Name: <%= f.text_field :name %>
  <%= render  partial: 'project', :locals=>{:f => f} %>
<% end %>

app/views/projects/show.html.erb
<br></br>
<h3> <%= @project.name %> | <%= @project.house.address%> </h3>

<h4>
  <%= form_for @project do |f|%>
      <%= f.select :status, ['not started', 'in progress', 'complete']%>
      <%= f.submit "set status" %>
    <% end %> 
</h4>

 <%= render 'shared/error_messages', object: @project %>

<ul>
  <% @project.items.each do |item| %>
    <li><%= material_lookup(item) %></li>
  <% end %>
</ul>

<p>
   <%= link_to "Back To Address", house_path(@project.house) %> |
   <%= link_to "Edit Project Name", edit_project_path %> |
   <%= link_to "Update Items List", project_items_path(@project) %> |
   <%= link_to "Remove Project",  project_path(@project), method: :delete %>
</p>