config/routes.rb
Rails.application.routes.draw do

  root 'houses#index'
  resources :houses do
      resources :projects, only: [:index, :new]
  end


  resources :projects do
    resources :items, only: [:index]
  end
  get 'insufficient_quantity', to: 'projects#insufficient_quantity'

  resources :materials do
    collection do
      delete'remove_multiple_materials' => 'materials#remove_multiple'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"} do
    resources :users, :only => [:show]
  end

  get '/projects/materials/new' => 'materials#new'
  get '/materials/:id/blah', to: 'materials#blah'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :items
  validates :name, presence: true
  validates :name, uniqueness: true
  
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController

  def index
    @materials = Material.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @materials.to_json }
    end
  end

  def show
    @material = Material.find(params[:id])
  end

  def new
    @material = Material.new()
  end

  def create
    @material = Material.new()
    @material.update(material_params)
    if @material.errors.messages != {}
      render 'new'
    else
      render json: @material, status: 201
    end

  end

  def edit
    @material = Material.find(params[:id])
  end

  def update
    @material = Material.find(params[:id])
    @material.update(material_params)

    if @material.errors.messages != {}
      render 'edit'
    else
      redirect_to material_path(@material)
    end

  end

  def destroy
    @material = Material.find(params[:id])
    @material.delete
    @material.save
    redirect_to materials_path
  end

private

  def material_params
    params.require(:material).permit(:name, :quantity_on_hand)
  end

end

app/helpers/materials_helper.rb
module MaterialsHelper

  def material_qoh(material_id)
    Material.find(material_id).quantity_on_hand
  end

  def material_being_used?
    if Project.all.find_all{|project| project.materials.include?(@material)} == []
      link_to "Remove #{@material.name}",  material_path(@material), method: :delete
    end
  end

end

app/views/materials/_form.html.erb
<%= form_for @material do |f| %>
  <p>
    <%= render 'shared/error_messages', object: @material %>
    <%= f.label "Name" %>
    <%= f.text_field :name %>
    <%= f.label "Quantity On Hand" %>
    <%= f.number_field :quantity_on_hand, min: 0, placeholder: @material.quantity_on_hand %>
  </p>
  <%= f.submit %>
<% end %>

app/views/materials/edit.html.erb
<h2>Editing Material: <%= @material.name %></h2>
<%= render 'form' %>

app/views/materials/index.html.erb
<h3>Materials List</h3>

<div id="materials">
</div>

<%= link_to "Add New Materials", new_material_path %>

<button id="filter">Filter Less Than 100</button>

app/views/materials/new.html.erb
<h3>Add Material(s)</h3>
<div id="materialResult">
  <ul>
    <li><h4 id="materialName"></h4> <p id="materialQuantityOnHand"></p></li>
  </ul>
</div>

<%= render 'form' %>

<script id="material-template" type="text/x-handlebars-template">
  <div class="entry">
    {{#if name}}
    <h4>{{name}} : Quantity on Hand - {{quantityOnHand}}</h4>
    {{else}}
    {{{alert}}}
    {{/if}}
  </div>
</script>

<script type="text/javascript" charset="utf-8">
$(function () {
  $('.new_material').on("submit", function(event) {
    event.preventDefault();
    var values = $(this).serialize();
    var materialID = this.id;
    var material = $.post('/materials', values);
      material.done(function(data) {
        parseMaterial(data)
      });
      return false; //Super Important! This returns the form submit button to original state by NOT submitting the form. (sounds strange...I know but it works)
    });
  });
</script>

app/views/materials/show.html.erb
<h3><%= @material.name %></h3>
<h4> Current Inventory: <%= @material.quantity_on_hand%></h4>

<p><%= material_being_used? %></p>

<ul>
  <% Project.all.each do |project| %>
    <% if project.materials.exists?(@material.id) %>
        <li>Needed for: <%= link_to project.name, project_path(project) %></li>
    <% end %>
  <% end %>
</ul>

<p><%= link_to "Edit Material", edit_material_path %></p>

app/views/materials/temp_form.erb
<form class="new_material" id="new_material" action="/materials" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="7G7GU53n8r2T7pub11ALKveqLEa+/HVdSkjHR7+CyO7sWrqaaHioOEmCieKnkKu9rIhWtsAgKoZBjkXcsUWIQg==">
  <p>


    <label for="material_Name">Name</label>
    <input type="text" name="material[name]" id="material_name">
    <label for="material_Quantity On Hand">Quantity on hand</label>
    <input min="0" placeholder="0" type="number" value="0" name="material[quantity_on_hand]" id="material_quantity_on_hand">
  </p>
  <input type="submit" name="commit" value="Create Material" data-disable-with="Create Material">
</form>