config/routes.rb
Rails.application.routes.draw do

  root 'houses#index'
  resources :houses do
      resources :projects, only: [:index, :new]
  end


  resources :projects do
    resources :items, only: [:index]
  end
  get 'insufficient_quantity', to: 'projects#insufficient_quantity'

  resources :materials do
    collection do
      delete'remove_multiple_materials' => 'materials#remove_multiple'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"} do
    resources :users, :only => [:show]
  end

  get '/projects/materials/new' => 'materials#new'
  get '/materials/:id/blah', to: 'materials#blah'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <br></br>
  <nav>
    <% if !!current_user %>
      Currently logged in as: <%= current_user.email %> |
        <%= link_to("Sign out", destroy_user_session_path, :method => 'delete') %>
    <% end %>
  </nav>

  <small>
    Made possible through Flatiron learning wizardy
  </small>

</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top" style="background-color: #fff5dd" role="navigation">

    <ul>
      <h2>Home Improvement</h2>
      <% if !!current_user %>
        <%= link_to("Home", houses_path) %> |
        <%= link_to "Materials on hand", materials_path, :id => "materials_list"%> |
        <%= link_to("Insufficient quantity", insufficient_quantity_path )%>
      <% end %>
    </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>HomeImprovement</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>

    <%= render 'layouts/header' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
  
</html>